name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies & Build
        run: |
          npm install
          chmod -R +x node_modules/.bin
          npx vite build

      - name: Upload to Yandex Object Storage via AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_SECRET_KEY }}
          AWS_DEFAULT_REGION: ru-central1
        run: |
          aws --endpoint-url=https://storage.yandexcloud.net s3 sync dist/ s3://gurman-supermarket --delete