name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies & Build
        run: |
          npm install
          npm run build

      - name: Upload to Yandex Object Storage
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: gurman-supermarket
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_SECRET_KEY }}
          AWS_REGION: ru-central1
          SOURCE_DIR: 'dist'
          AWS_ENDPOINT: https://storage.yandexcloud.net